#ifndef EROFS_EXTRACT_COMMON_H
#define EROFS_EXTRACT_COMMON_H

// Return codes
#define RET_EXTRACT_DONE              0
#define RET_EXTRACT_INIT_FAIL         1
#define RET_EXTRACT_CONFIG_FAIL       2
#define RET_EXTRACT_CREATE_DIR_FAIL   3
#define RET_EXTRACT_INIT_NODE_FAIL    4
#define RET_EXTRACT_THREAD_NUM_ERROR  5

#endif // EROFS_EXTRACT_COMMON_H 