name: Build on Windows with MSYS2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows-msys2:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install MSYS2
        shell: pwsh
        run: |
          # Define installer URL (update to the latest version)
          $msys2_url = "https://repo.msys2.org/distrib/x86_64/msys2-x86_64-20230531.exe"
          $installer_path = "$env:USERPROFILE\msys2-installer.exe"
          
          # Download MSYS2 installer
          Invoke-WebRequest -Uri $msys2_url -OutFile $installer_path
          
          # Install MSYS2 silently
          Start-Process -FilePath $installer_path -ArgumentList "/S" -Wait -NoNewWindow
          
          # Initialize MSYS2 (update package database)
          & "C:\msys64\usr\bin\bash.exe" -c "pacman -Sy --noconfirm"

      - name: Update MSYS2 and Install Packages
        shell: bash
        run: |
          # Update the package database and core system packages
          pacman -Su --noconfirm

          # Install required development packages
          pacman -S --noconfirm make gcc autoconf automake libtool pkg-config git mingw-w64-x86_64-toolchain

      - name: Add MSYS2 to PATH
        shell: pwsh
        run: |
          $msys2_bin = "C:\msys64\usr\bin"
          $msys2_mingw64_bin = "C:\msys64\mingw64\bin"
          $env:Path += ";$msys2_bin;$msys2_mingw64_bin"
          [Environment]::SetEnvironmentVariable("Path", $env:Path, "Process")

      - name: Verify MSYS2 Installation
        shell: bash
        run: |
          bash --version
          make --version
          gcc --version

      - name: Make Build Scripts Executable
        shell: bash
        run: |
          chmod +x autogen.sh
          chmod +x build.sh

      - name: Run Build Script
        shell: bash
        run: |
          ./autogen.sh
          ./configure --prefix=/c/build
          make
          make install

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: C:\build